### ISSUE TITLE
Task 1: Modifying a Shared Markdown File

### ISSUE THREAD

**Issue by emmet0r** [emmet0r/awesome-foss#15]
Setup repository with instructions for workshop/event participants to modify a shared Markdown file. 

Our brainstorm notes so far:
- consider using a lighthearted made-up poem or story as source material to edit (idea borrowed from [Sal Kimmich](https://www.linkedin.com/in/salkimmich/)!)
- we provide short starter poem/story for others to build on with goal of avoiding merge conflicts; maybe add one line at a time in a way that doesn't depend on other lines?
- suggest that contributors follow rules (rhyming, # syllables, etc.) to modify written English text, similar to how code must follow rules

**Comment by emmet0r** [comment]
I think this activity incorporates the following learning goals from your brainstorm, @Nandinisaagar ☺️ But we can always adjust if we think it makes sense - 

1. Creating a repository
2. Forking a repository
3. Creating a branch
4. Creating a pull request

**Comment by Nandinisaagar** [comment]
https://github.com/awesomefoss/Scavenger-Hunt-Task-1
