### ISSUE TITLE
Task 2: Contributing to a Mock Project

### ISSUE THREAD

**Issue by emmet0r** [emmet0r/awesome-foss#16]
Setup a project repository to be used for scavenger hunt workshop/event that invites participants to work on a shared sample project.

Our brainstorm notes so far:
- maybe use a simple collection of website files (HTML, CSS, JavaScript only - nothing complicated - deployed with GitHub Pages)
- consider asking users to make small changes first that _won't_ cause conflicts... then introduce merge conflicts through a later change to the code
- I teach with a repo of a similar type that works pretty well (based on one from OpenHatch; see closed issues and earlier code versions for what it looked like before students worked on it): https://github.com/emmet0r/git-playground
- current instructions used for my reference teaching activity/repo: https://trello.com/c/YqdFlEKb/35-intro-sample-project
- introduce participants to forking on GitHub, then cloning to their machine, making changes, pushing them, and making a PR

**Comment by Nandinisaagar** [comment]
https://github.com/awesomefoss/Scavenger-Hunt-Task-2
