### ISSUE TITLE
(Blog 3) Getting started with Git and GitHub

### ISSUE THREAD

**Issue by emmet0r** [emmet0r/awesome-foss#8]

**Comment by emmet0r** [comment]
Due date moved to new "deadline" field 🎉

**Comment by Nandinisaagar** [comment]
Deployed blog 3. will be working on the code blocks 
Desired output:

<img width="868" alt="Screenshot 2023-06-22 at 11 07 26 PM" src="https://github.com/emmet0r/awesome-foss/assets/96643952/b80bcc39-2b14-44d6-b457-351a23a15212">
